title: Asset
modelClass: NielsVanDenDries\Assetmanagement\Models\Asset
list: $/nielsvandendries/assetmanagement/models/asset/columns.yaml
recordUrl: 'nielsvandendries/assetmanagement/asset/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
