title: Users
modelClass: NielsVanDenDries\Assetmanagement\Models\Users
list: $/nielsvandendries/assetmanagement/models/users/columns.yaml
recordUrl: 'nielsvandendries/assetmanagement/users/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
