plugin:
    name: 'nielsvandendries.assetmanagement::lang.plugin.name'
    description: 'nielsvandendries.assetmanagement::lang.plugin.description'
    author: 'Niels van den Dries'
    icon: oc-icon-compass
    homepage: 'https://nvandendries.nl'
permissions:
    manager:
        tab: 'nielsvandendries.assetmanagement::lang.plugin.name'
        label: 'Asset Management'
navigation:
    main-menu-item:
        label: 'Asset Management'
        url: /
        icon: icon-compass
        permissions:
            - manager
        sideMenu:
            side-menu-item:
                label: Assets
                url: nielsvandendries/assetmanagement/asset
                icon: icon-dropbox
                permissions:
                    - manager
            side-menu-item2:
                label: Owners
                url: nielsvandendries/assetmanagement/owners
                icon: icon-users
                permissions:
                    - manager
            side-menu-item3:
                label: Users
                url: nielsvandendries/assetmanagement/users
                icon: icon-user-md
                permissions:
                    - manager
