title: Owners
modelClass: NielsVanDenDries\Assetmanagement\Models\Owners
list: $/nielsvandendries/assetmanagement/models/owners/columns.yaml
recordUrl: 'nielsvandendries/assetmanagement/owners/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
