name: Settings
form: $/nielsvandendries/assetmanagement/models/settings/fields.yaml
modelClass: NielsVanDenDries\Assetmanagement\Models\Settings
defaultRedirect: nielsvandendries/assetmanagement/settings
create:
    redirect: 'nielsvandendries/assetmanagement/settings/update/:id'
    redirectClose: nielsvandendries/assetmanagement/settings
update:
    redirect: nielsvandendries/assetmanagement/settings
    redirectClose: nielsvandendries/assetmanagement/settings
